function Hd = untitled
%UNTITLED Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 11-Jul-2019 17:39:45

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

N  = 10;    % Order
Fc = 5000;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
% Hd1 = design(h, 'butter');
% disp(Hd1);
Hd2 = dsp.LowpassFilter('SampleRate',Fs, 'FilterOrder', N, 'PassbandFrequency', Fc, 'FilterType', 'IIR', 'DesignForMinimumOrder',false);
% disp(Hd2);
% LP_IIR = dsp.LowpassFilter('SampleRate',Fs,'FilterType','IIR',...
%     'DesignForMinimumOrder',false,'FilterOrder',N,...
%     'PassbandFrequency',Fc);
hfvt = fvtool(Hd2,'Fs',Fs);
% [EOF]